const pokeData = [
  {
    rank: 4,
    pokemon: [
      {
        id: 1,
        name: "Klefki",
        item: "Light Clay",
        ability: "Prankster",
        tera: "Ghost",
        moves: ["Flash Cannon", "Reflect", "Light Screen", "Thunder Wave"],
      },
      {
        id: 2,
        name: "Heat Rotom",
        item: "Sitrus Berry",
        ability: "Levitate",
        tera: "Electric",
        moves: ["Overheat", "Thunderbolt", "Will-O-Wisp", "Protect"],
      },
      {
        id: 3,
        name: "Amoonguss",
        item: "Rocky Helmet",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Pollen Puff", "Spore", "Rage Powder", "Protect"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Dazzling Gleam", "Protect"],
      },
      {
        id: 5,
        name: "Paldean Tauros Aqua Breed",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Steel",
        moves: ["Wave Crash", "Close Combat", "Aqua Jet", "Protect"],
      },
      {
        id: 6,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Water",
        moves: ["Throat Chop", "Stomping Tantrum", "Ruination", "Fissure"],
      },
    ],
  },
  {
    rank: 8,
    pokemon: [
      {
        id: 1,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Dark Pulse", "Snarl", "Heat Wave", "Overheat"],
      },
      {
        id: 2,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Shadow Ball", "Moonblast", "Power Gem"],
      },
      {
        id: 3,
        name: "Dragonite",
        item: "Choice Band",
        ability: "Inner Focus",
        tera: "Normal",
        moves: ["Extreme Speed", "Earthquake", "Dragon Claw", "Fire Punch"],
      },
      {
        id: 4,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Fighting",
        moves: ["Sucker Punch", "Ice Spinner", "Sacred Sword", "Protect"],
      },
      {
        id: 5,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Pollen Puff", "Rage Powder", "Spore", "Protect"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
    ],
  },
  {
    rank: 1,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Ice Spinner", "Sucker Punch", "Protect", "Swords Dance"],
      },
      {
        id: 2,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Poison",
        moves: ["Stomping Tantrum", "Ruination", "Rock Tomb", "Fissure"],
      },
      {
        id: 3,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Shadow Ball", "Moonblast", "Power Gem"],
      },
      {
        id: 5,
        name: "Annihilape",
        item: "Leftovers",
        ability: "Defiant",
        tera: "Fire",
        moves: ["Drain Punch", "Rage Fist", "Bulk Up", "Protect"],
      },
      {
        id: 6,
        name: "Dragonite",
        item: "Choice Band",
        ability: "Multiscale",
        tera: "Normal",
        moves: ["Extreme Speed", "Stomping Tantrum", "Ice Spinner", "Low Kick"],
      },
    ],
  },
  {
    rank: 17,
    pokemon: [
      {
        id: 1,
        name: "Indeedee ♀",
        item: "Terrain Extender",
        ability: "Psychic Surge",
        tera: "Dragon",
        moves: ["Psychic", "Trick Room", "Follow Me", "Protect"],
      },
      {
        id: 2,
        name: "Armarouge",
        item: "Psychic Seed",
        ability: "Flash Fire",
        tera: "Steel",
        moves: ["Calm Mind", "Heat Wave", "Expanding Force", "Protect"],
      },
      {
        id: 3,
        name: "Baxcalibur",
        item: "Loaded Dice",
        ability: "Thermal Exchange",
        tera: "Poison",
        moves: ["Glaive Rush", "Brick Break", "Protect", "Icicle Spear"],
      },
      {
        id: 4,
        name: "Sandy Shocks",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Bug",
        moves: ["Discharge", "Earth Power", "Thunderbolt", "Protect"],
      },
      {
        id: 5,
        name: "Maushold",
        item: "Sitrus Berry",
        ability: "Friend Guard",
        tera: "Bug",
        moves: ["Protect", "Follow Me", "Encore", "Super Fang"],
      },
      {
        id: 6,
        name: "Espathra",
        item: "Focus Sash",
        ability: "Speed Boost",
        tera: "Flying",
        moves: ["Lumina Crash", "Feather Dance", "Tera Blast", "Protect"],
      },
    ],
  },
  {
    rank: 10,
    pokemon: [
      {
        id: 1,
        name: "Ting-Lu",
        item: "Figy Berry",
        ability: "Vessel of Ruin",
        tera: "Fairy",
        moves: ["Throat Chop", "Stomping Tantrum", "Protect", "Tera Blast"],
      },
      {
        id: 2,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Stomping Tantrum", "Fake Out"],
      },
      {
        id: 3,
        name: "Baxcalibur",
        item: "Life Orb",
        ability: "Thermal Exchange",
        tera: "Poison",
        moves: ["Protect", "Glaive Rush", "Ice Shard", "Icicle Crash"],
      },
      {
        id: 4,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Protect", "Wave Crash", "Jet Punch", "Haze"],
      },
      {
        id: 5,
        name: "Arcanine",
        item: "Sitrus Berry",
        ability: "Intimidate",
        tera: "Grass",
        moves: ["Flare Blitz", "Will-O-Wisp", "Snarl", "Protect"],
      },
      {
        id: 6,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Icy Wind", "Protect"],
      },
    ],
  },
  {
    rank: 13,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Fighting",
        moves: ["Ice Spinner", "Sucker Punch", "Crunch", "Protect"],
      },
      {
        id: 2,
        name: "Scizor",
        item: "Life Orb",
        ability: "Technician",
        tera: "Fire",
        moves: ["Bullet Punch", "Pounce", "Trailblaze", "Protect"],
      },
      {
        id: 3,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
      {
        id: 4,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Ground",
        moves: ["Heavy Slam", "Snarl", "Stomping Tantrum", "Earthquake"],
      },
      {
        id: 5,
        name: "Flutter Mane",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Grass",
        moves: ["Shadow Ball", "Protect", "Perish Song", "Moonblast"],
      },
      {
        id: 6,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Spore", "Pollen Puff", "Protect", "Rage Powder"],
      },
    ],
  },
  {
    rank: 16,
    pokemon: [
      {
        id: 1,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Shadow Ball", "Perish Song", "Protect"],
      },
      {
        id: 2,
        name: "Grimmsnarl",
        item: "Light Clay",
        ability: "Prankster",
        tera: "Grass",
        moves: ["Spirit Break", "Fake Out", "Light Screen", "Reflect"],
      },
      {
        id: 3,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Close Combat", "Protect"],
      },
      {
        id: 4,
        name: "Garganacl",
        item: "Black Sludge",
        ability: "Purifying Salt",
        tera: "Poison",
        moves: ["Salt Cure", "Recover", "Wide Guard", "Protect"],
      },
      {
        id: 5,
        name: "Iron Thorns",
        item: "Choice Band",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Rock Slide", "Earthquake", "Wild Charge", "Tera Blast"],
      },
      {
        id: 6,
        name: "Volcarona",
        item: "Leftovers",
        ability: "Flame Body",
        tera: "Dragon",
        moves: ["Heat Wave", "Bug Buzz", "Quiver Dance", "Protect"],
      },
    ],
  },
  {
    rank: 5,
    pokemon: [
      {
        id: 1,
        name: "Scizor",
        item: "Clear Amulet",
        ability: "Technician",
        tera: "Fire",
        moves: ["Protect", "U-turn", "Iron Head", "Bullet Punch"],
      },
      {
        id: 2,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Protect", "Haze", "Jet Punch", "Wave Crash"],
      },
      {
        id: 3,
        name: "Pelipper",
        item: "Sitrus Berry",
        ability: "Drizzle",
        tera: "Flying",
        moves: ["Protect", "Tailwind", "Hurricane", "Hydro Pump"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Psyshock", "Moonblast", "Dazzling Gleam", "Shadow Ball"],
      },
      {
        id: 5,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Volt Switch", "Fake Out"],
      },
      {
        id: 6,
        name: "Chi-Yu",
        item: "Focus Sash",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Snarl", "Tera Blast", "Heat Wave", "Protect"],
      },
    ],
  },
  {
    rank: 21,
    pokemon: [
      {
        id: 1,
        name: "Iron Jugulis",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Steel",
        moves: ["Tailwind", "Air Slash", "Snarl", "Protect"],
      },
      {
        id: 2,
        name: "Gholdengo",
        item: "Choice Specs",
        ability: "Good as Gold",
        tera: "Steel",
        moves: ["Make It Rain", "Shadow Ball", "Power Gem", "Trick"],
      },
      {
        id: 3,
        name: "Chi-Yu",
        item: "Assault Vest",
        ability: "Beads of Ruin",
        tera: "Water",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Tera Blast"],
      },
      {
        id: 4,
        name: "Baxcalibur",
        item: "Dragon Fang",
        ability: "Thermal Exchange",
        tera: "Poison",
        moves: ["Glaive Rush", "Icicle Crash", "Ice Shard", "Protect"],
      },
      {
        id: 5,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Spore", "Rage Powder", "Pollen Puff", "Protect"],
      },
      {
        id: 6,
        name: "Mimikyu",
        item: "Life Orb",
        ability: "Disguise",
        tera: "Fairy",
        moves: ["Play Rough", "Shadow Claw", "Shadow Sneak", "Trick Room"],
      },
    ],
  },
  {
    rank: 7,
    pokemon: [
      {
        id: 1,
        name: "Annihilape",
        item: "Lum Berry",
        ability: "Defiant",
        tera: "Water",
        moves: ["Rage Fist", "Drain Punch", "Bulk Up", "Protect"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Safety Goggles",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Protect"],
      },
      {
        id: 3,
        name: "Azumarill",
        item: "Life Orb",
        ability: "Huge Power",
        tera: "Water",
        moves: ["Aqua Jet", "Liquidation", "Play Rough", "Ice Spinner"],
      },
      {
        id: 4,
        name: "Glimmora",
        item: "Focus Sash",
        ability: "Toxic Debris",
        tera: "Grass",
        moves: ["Mortal Spin", "Earth Power", "Power Gem", "Spiky Shield"],
      },
      {
        id: 5,
        name: "Wo-Chien",
        item: "Leftovers",
        ability: "Tablets of Ruin",
        tera: "Poison",
        moves: ["Leech Seed", "Ruination", "Pollen Puff", "Protect"],
      },
      {
        id: 6,
        name: "Flutter Mane",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Substitute", "Protect"],
      },
    ],
  },
  {
    rank: 14,
    pokemon: [
      {
        id: 1,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Fire",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Overheat"],
      },
      {
        id: 2,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Shadow Ball", "Dazzling Gleam", "Moonblast", "Protect"],
      },
      {
        id: 3,
        name: "Amoonguss",
        item: "Mental Herb",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Rage Powder", "Spore", "Pollen Puff", "Leaf Storm"],
      },
      {
        id: 4,
        name: "Gyarados",
        item: "Lum Berry",
        ability: "Intimidate",
        tera: "Flying",
        moves: ["Waterfall", "Tera Blast", "Dragon Dance", "Protect"],
      },
      {
        id: 5,
        name: "Iron Hands",
        item: "Safety Goggles",
        ability: "Quark Drive",
        tera: "Fire",
        moves: ["Fake Out", "Drain Punch", "Wild Charge", "Protect"],
      },
      {
        id: 6,
        name: "Ting-Lu",
        item: "Weakness Policy",
        ability: "Vessel of Ruin",
        tera: "Poison",
        moves: ["Stomping Tantrum", "Heavy Slam", "Ruination", "Snarl"],
      },
    ],
  },
  {
    rank: 18,
    pokemon: [
      {
        id: 1,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Poison",
        moves: ["Heavy Slam", "Stomping Tantrum", "Ruination", "Snarl"],
      },
      {
        id: 2,
        name: "Scream Tail",
        item: "Figy Berry",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Protect", "Play Rough", "Wish", "Howl"],
      },
      {
        id: 3,
        name: "Arcanine",
        item: "Sitrus Berry",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Protect", "Extreme Speed", "Flare Blitz", "Will-O-Wisp"],
      },
      {
        id: 4,
        name: "Iron Bundle",
        item: "Focus Sash",
        ability: "Quark Drive",
        tera: "Ice",
        moves: ["Icy Wind", "Freeze-Dry", "Hydro Pump", "Protect"],
      },
      {
        id: 5,
        name: "Annihilape",
        item: "Leftovers",
        ability: "Defiant",
        tera: "Fire",
        moves: ["Bulk Up", "Rage Fist", "Drain Punch", "Protect"],
      },
      {
        id: 6,
        name: "Amoonguss",
        item: "Rocky Helmet",
        ability: "Regenerator",
        tera: "Dark",
        moves: ["Protect", "Rage Powder", "Spore", "Pollen Puff"],
      },
    ],
  },
  {
    rank: 6,
    pokemon: [
      {
        id: 1,
        name: "Lilligant",
        item: "Wide Lens",
        ability: "Chlorophyll",
        tera: "Ghost",
        moves: ["Leaf Storm", "Sleep Powder", "After You", "Protect"],
      },
      {
        id: 2,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Ice Shard", "Icicle Crash", "Crunch", "Protect"],
      },
      {
        id: 3,
        name: "Torkoal",
        item: "Charcoal",
        ability: "Drought",
        tera: "Fire",
        moves: ["Eruption", "Flamethrower", "Earth Power", "Protect"],
      },
      {
        id: 4,
        name: "Dragonite",
        item: "Safety Goggles",
        ability: "Inner Focus",
        tera: "Normal",
        moves: ["Extreme Speed", "Ice Spinner", "Earthquake", "Tailwind"],
      },
      {
        id: 5,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Water",
        moves: ["Heat Wave", "Dark Pulse", "Psychic", "Tera Blast"],
      },
      {
        id: 6,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Steel",
        moves: ["Shadow Ball", "Moonblast", "Power Gem", "Dazzling Gleam"],
      },
    ],
  },
  {
    rank: 11,
    pokemon: [
      {
        id: 1,
        name: "Scizor",
        item: "Leftovers",
        ability: "Technician",
        tera: "Fire",
        moves: ["U-turn", "Bullet Punch", "Brick Break", "Protect"],
      },
      {
        id: 2,
        name: "Tsareena",
        item: "Choice Band",
        ability: "Queenly Majesty",
        tera: "Fairy",
        moves: ["Trop Kick", "Zen Headbutt", "Play Rough", "U-turn"],
      },
      {
        id: 3,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Dazzling Gleam", "Shadow Ball", "Psyshock"],
      },
      {
        id: 4,
        name: "Pelipper",
        item: "Sitrus Berry",
        ability: "Drizzle",
        tera: "Flying",
        moves: ["Hurricane", "Hydro Pump", "Tailwind", "Wide Guard"],
      },
      {
        id: 5,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Fake Out", "Wild Charge", "Drain Punch", "Volt Switch"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Haze", "Protect"],
      },
    ],
  },
  {
    rank: 15,
    pokemon: [
      {
        id: 1,
        name: "Glimmora",
        item: "Assault Vest",
        ability: "Toxic Debris",
        tera: "Water",
        moves: ["Power Gem", "Sludge Bomb", "Energy Ball", "Earth Power"],
      },
      {
        id: 2,
        name: "Grimmsnarl",
        item: "Focus Sash",
        ability: "Prankster",
        tera: "Fire",
        moves: ["Spirit Break", "Scary Face", "Parting Shot", "Fake Out"],
      },
      {
        id: 3,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Fire",
        moves: ["Shadow Ball", "Moonblast", "Mystical Fire", "Protect"],
      },
      {
        id: 4,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Hydro Pump", "Freeze-Dry", "Icy Wind", "Protect"],
      },
      {
        id: 5,
        name: "Chi-Yu",
        item: "Sitrus Berry",
        ability: "Beads of Ruin",
        tera: "Water",
        moves: ["Heat Wave", "Snarl", "Will-O-Wisp", "Protect"],
      },
      {
        id: 6,
        name: "Klefki",
        item: "Light Clay",
        ability: "Prankster",
        tera: "Fire",
        moves: ["Dazzling Gleam", "Reflect", "Light Screen", "Thunder Wave"],
      },
    ],
  },
  {
    rank: 19,
    pokemon: [
      {
        id: 1,
        name: "Talonflame",
        item: "Covert Cloak",
        ability: "Gale Wings",
        tera: "Ghost",
        moves: ["Brave Bird", "Tailwind", "Quick Guard", "Will-O-Wisp"],
      },
      {
        id: 2,
        name: "Great Tusk",
        item: "Choice Scarf",
        ability: "Protosynthesis",
        tera: "Ground",
        moves: ["Headlong Rush", "Close Combat", "Earthquake", "Rock Slide"],
      },
      {
        id: 3,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Rage Powder", "Pollen Puff", "Spore", "Protect"],
      },
      {
        id: 4,
        name: "Chi-Yu",
        item: "Life Orb",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Protect"],
      },
      {
        id: 5,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Dazzling Gleam", "Energy Ball"],
      },
      {
        id: 6,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Ghost",
        moves: ["Hydro Pump", "Freeze-Dry", "Icy Wind", "Protect"],
      },
    ],
  },
  {
    rank: 9,
    pokemon: [
      {
        id: 1,
        name: "Wo-Chien",
        item: "Leftovers",
        ability: "Tablets of Ruin",
        tera: "Fire",
        moves: ["Protect", "Giga Drain", "Pollen Puff", "Leech Seed"],
      },
      {
        id: 2,
        name: "Glimmora",
        item: "Focus Sash",
        ability: "Toxic Debris",
        tera: "Grass",
        moves: ["Sludge Bomb", "Energy Ball", "Power Gem", "Spiky Shield"],
      },
      {
        id: 3,
        name: "Gothitelle",
        item: "Sitrus Berry",
        ability: "Shadow Tag",
        tera: "Normal",
        moves: ["Protect", "Fake Out", "Psychic", "Heal Pulse"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Steel",
        moves: ["Protect", "Perish Song", "Dazzling Gleam", "Shadow Ball"],
      },
      {
        id: 5,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Protect", "Flare Blitz", "Extreme Speed", "Will-O-Wisp"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Protect", "Jet Punch", "Wave Crash", "Haze"],
      },
    ],
  },
  {
    rank: 24,
    pokemon: [
      {
        id: 1,
        name: "Dragonite",
        item: "Assault Vest",
        ability: "Multiscale",
        tera: "Normal",
        moves: ["Dragon Claw", "Extreme Speed", "Earthquake", "Ice Spinner"],
      },
      {
        id: 2,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Dark",
        moves: ["Protect", "Ice Spinner", "Throat Chop", "Sucker Punch"],
      },
      {
        id: 3,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Ice",
        moves: ["Freeze-Dry", "Icy Wind", "Hydro Pump", "Protect"],
      },
      {
        id: 4,
        name: "Chi-Yu",
        item: "Life Orb",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Heat Wave", "Dark Pulse", "Tera Blast", "Protect"],
      },
      {
        id: 5,
        name: "Amoonguss",
        item: "Covert Cloak",
        ability: "Regenerator",
        tera: "Dark",
        moves: ["Rage Powder", "Spore", "Clear Smog", "Pollen Puff"],
      },
      {
        id: 6,
        name: "Annihilape",
        item: "Choice Scarf",
        ability: "Defiant",
        tera: "Fighting",
        moves: ["Phantom Force", "Close Combat", "Final Gambit", "U-turn"],
      },
    ],
  },
  {
    rank: 3,
    pokemon: [
      {
        id: 1,
        name: "Dondozo",
        item: "Leftovers",
        ability: "Unaware",
        tera: "Grass",
        moves: ["Wave Crash", "Body Press", "Earthquake", "Protect"],
      },
      {
        id: 2,
        name: "Tatsugiri",
        item: "Choice Scarf",
        ability: "Commander",
        tera: "Ghost",
        moves: ["Icy Wind", "Muddy Water", "Draco Meteor", "Tera Blast"],
      },
      {
        id: 3,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Ghost",
        moves: ["Freeze-Dry", "Encore", "Icy Wind", "Protect"],
      },
      {
        id: 4,
        name: "Chi-Yu",
        item: "Life Orb",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Dark Pulse", "Heat Wave", "Tera Blast", "Protect"],
      },
      {
        id: 5,
        name: "Kingambit",
        item: "Lum Berry",
        ability: "Defiant",
        tera: "Ghost",
        moves: ["Assurance", "Iron Head", "Sucker Punch", "Quick Guard"],
      },
      {
        id: 6,
        name: "Pawmot",
        item: "Focus Sash",
        ability: "Natural Cure",
        tera: "Electric",
        moves: ["Close Combat", "Double Shock", "Revival Blessing", "Fake Out"],
      },
    ],
  },
  {
    rank: 12,
    pokemon: [
      {
        id: 1,
        name: "Gastrodon",
        item: "Wiki Berry",
        ability: "Storm Drain",
        tera: "Fire",
        moves: ["Earth Power", "Stockpile", "Recover", "Clear Smog"],
      },
      {
        id: 2,
        name: "Maushold",
        item: "Wide Lens",
        ability: "Technician",
        tera: "Ghost",
        moves: ["Population Bomb", "Encore", "Follow Me", "Taunt"],
      },
      {
        id: 3,
        name: "Arcanine",
        item: "Iapapa Berry",
        ability: "Intimidate",
        tera: "Flying",
        moves: ["Flare Blitz", "Extreme Speed", "Will-O-Wisp", "Morning Sun"],
      },
      {
        id: 4,
        name: "Annihilape",
        item: "Figy Berry",
        ability: "Defiant",
        tera: "Fire",
        moves: ["Drain Punch", "Rage Fist", "Encore", "Bulk Up"],
      },
      {
        id: 5,
        name: "Farigiraf",
        item: "Safety Goggles",
        ability: "Armor Tail",
        tera: "Steel",
        moves: ["Psychic", "Skill Swap", "Trick Room", "Energy Ball"],
      },
      {
        id: 6,
        name: "Great Tusk",
        item: "Choice Scarf",
        ability: "Protosynthesis",
        tera: "Fire",
        moves: ["Headlong Rush", "Close Combat", "Rock Slide", "Brick Break"],
      },
    ],
  },
  {
    rank: 25,
    pokemon: [
      {
        id: 1,
        name: "Lycanroc",
        item: "Focus Sash",
        ability: "Sand Rush",
        tera: "Rock",
        moves: ["Protect", "Rock Slide", "Close Combat", "Quick Guard"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Flamethrower"],
      },
      {
        id: 3,
        name: "Tyranitar",
        item: "Assault Vest",
        ability: "Sand Stream",
        tera: "Flying",
        moves: ["Rock Slide", "Crunch", "Heavy Slam", "Low Kick"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Steel",
        moves: ["Shadow Ball", "Dazzling Gleam", "Icy Wind", "Moonblast"],
      },
      {
        id: 5,
        name: "Gallade",
        item: "Clear Amulet",
        ability: "Sharpness",
        tera: "Fire",
        moves: ["Psycho Cut", "X-Scissor", "Sacred Sword", "Wide Guard"],
      },
      {
        id: 6,
        name: "Indeedee ♀",
        item: "Safety Goggles",
        ability: "Psychic Surge",
        tera: "Normal",
        moves: ["Follow Me", "Heal Pulse", "Psychic", "Protect"],
      },
    ],
  },
  {
    rank: 2,
    pokemon: [
      {
        id: 1,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Pollen Puff", "Spore", "Rage Powder", "Protect"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Safety Goggles",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Dark Pulse", "Overheat", "Protect"],
      },
      {
        id: 3,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Grass",
        moves: ["Throat Chop", "Heavy Slam", "Fissure", "Stomping Tantrum"],
      },
      {
        id: 4,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Haze", "Protect"],
      },
      {
        id: 5,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Steel",
        moves: ["Moonblast", "Dazzling Gleam", "Shadow Ball", "Power Gem"],
      },
      {
        id: 6,
        name: "Iron Treads",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Ground",
        moves: ["Heavy Slam", "Stomping Tantrum", "Ice Spinner", "Protect"],
      },
    ],
  },
  {
    rank: 20,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Flying",
        moves: ["Protect", "Icy Wind", "Haze", "Ruination"],
      },
      {
        id: 2,
        name: "Dragonite",
        item: "Lum Berry",
        ability: "Multiscale",
        tera: "Flying",
        moves: ["Protect", "Extreme Speed", "Tera Blast", "Stomping Tantrum"],
      },
      {
        id: 3,
        name: "Iron Jugulis",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Flying",
        moves: ["Protect", "Tailwind", "Snarl", "Air Slash"],
      },
      {
        id: 4,
        name: "Great Tusk",
        item: "Clear Amulet",
        ability: "Protosynthesis",
        tera: "Ground",
        moves: ["Protect", "Earthquake", "Headlong Rush", "Ice Spinner"],
      },
      {
        id: 5,
        name: "Chi-Yu",
        item: "Safety Goggles",
        ability: "Beads of Ruin",
        tera: "Water",
        moves: ["Protect", "Dark Pulse", "Heat Wave", "Overheat"],
      },
      {
        id: 6,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Dazzling Gleam", "Power Gem"],
      },
    ],
  },
  {
    rank: 26,
    pokemon: [
      {
        id: 1,
        name: "Armarouge",
        item: "Safety Goggles",
        ability: "Flash Fire",
        tera: "Grass",
        moves: ["Armor Cannon", "Expanding Force", "Energy Ball", "Protect"],
      },
      {
        id: 2,
        name: "Dedenne",
        item: "Sitrus Berry",
        ability: "Cheek Pouch",
        tera: "Rock",
        moves: ["Nuzzle", "Super Fang", "Charm", "Eerie Impulse"],
      },
      {
        id: 3,
        name: "Tyranitar",
        item: "Assault Vest",
        ability: "Sand Stream",
        tera: "Ghost",
        moves: ["Earthquake", "Rock Slide", "Shadow Claw", "Snarl"],
      },
      {
        id: 4,
        name: "Scizor",
        item: "Clear Amulet",
        ability: "Technician",
        tera: "Dark",
        moves: ["Close Combat", "Bullet Punch", "Thief", "Protect"],
      },
      {
        id: 5,
        name: "Iron Bundle",
        item: "Focus Sash",
        ability: "Quark Drive",
        tera: "Water",
        moves: ["Freeze-Dry", "Chilling Water", "Ice Spinner", "Protect"],
      },
      {
        id: 6,
        name: "Gyarados",
        item: "Covert Cloak",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Crunch", "Dragon Dance", "Protect", "Waterfall"],
      },
    ],
  },
  {
    rank: 22,
    pokemon: [
      {
        id: 1,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Protect", "Haze"],
      },
      {
        id: 2,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Fake Out", "Volt Switch"],
      },
      {
        id: 3,
        name: "Flutter Mane",
        item: "Choice Specs",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Dazzling Gleam", "Shadow Ball", "Power Gem"],
      },
      {
        id: 4,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Ice Spinner", "Sacred Sword", "Sucker Punch", "Protect"],
      },
      {
        id: 5,
        name: "Chi-Yu",
        item: "Safety Goggles",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Dark Pulse", "Will-O-Wisp", "Protect"],
      },
      {
        id: 6,
        name: "Indeedee ♀",
        item: "Sitrus Berry",
        ability: "Synchronize",
        tera: "Grass",
        moves: ["Follow Me", "Dazzling Gleam", "Trick Room", "Helping Hand"],
      },
    ],
  },
  {
    rank: 28,
    pokemon: [
      {
        id: 1,
        name: "Maushold",
        item: "Wide Lens",
        ability: "Friend Guard",
        tera: "Ghost",
        moves: ["Population Bomb", "Follow Me", "Beat Up", "Protect"],
      },
      {
        id: 2,
        name: "Annihilape",
        item: "Lum Berry",
        ability: "Defiant",
        tera: "Water",
        moves: ["Rage Fist", "Drain Punch", "Bulk Up", "Protect"],
      },
      {
        id: 3,
        name: "Chi-Yu",
        item: "Choice Specs",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Heat Wave", "Overheat", "Snarl", "Tera Blast"],
      },
      {
        id: 4,
        name: "Talonflame",
        item: "Covert Cloak",
        ability: "Gale Wings",
        tera: "Ghost",
        moves: ["Brave Bird", "Flare Blitz", "Tailwind", "Protect"],
      },
      {
        id: 5,
        name: "Baxcalibur",
        item: "Assault Vest",
        ability: "Thermal Exchange",
        tera: "Ground",
        moves: ["Ice Shard", "Icicle Crash", "Glaive Rush", "Earthquake"],
      },
      {
        id: 6,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Water",
        moves: ["Icy Wind", "Encore", "Freeze-Dry", "Hydro Pump"],
      },
    ],
  },
  {
    rank: 29,
    pokemon: [
      {
        id: 1,
        name: "Paldean Tauros Aqua Breed",
        item: "Mystic Water",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Raging Bull", "Aqua Jet", "Protect", "Close Combat"],
      },
      {
        id: 2,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Rage Powder", "Spore", "Protect", "Pollen Puff"],
      },
      {
        id: 3,
        name: "Garganacl",
        item: "Leftovers",
        ability: "Purifying Salt",
        tera: "Grass",
        moves: ["Salt Cure", "Recover", "Protect", "Wide Guard"],
      },
      {
        id: 4,
        name: "Ceruledge",
        item: "Clear Amulet",
        ability: "Flash Fire",
        tera: "Steel",
        moves: ["Bitter Blade", "Bulk Up", "Protect", "Shadow Sneak"],
      },
      {
        id: 5,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Sacred Sword", "Ice Spinner", "Protect", "Sucker Punch"],
      },
      {
        id: 6,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Fire",
        moves: ["Body Press", "Snarl", "Fissure", "Stomping Tantrum"],
      },
    ],
  },
  {
    rank: 23,
    pokemon: [
      {
        id: 1,
        name: "Flutter Mane",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Normal",
        moves: ["Moonblast", "Icy Wind", "Perish Song", "Protect"],
      },
      {
        id: 2,
        name: "Arcanine",
        item: "Mirror Herb",
        ability: "Intimidate",
        tera: "Normal",
        moves: ["Flare Blitz", "Will-O-Wisp", "Extreme Speed", "Protect"],
      },
      {
        id: 3,
        name: "Gothitelle",
        item: "Leftovers",
        ability: "Shadow Tag",
        tera: "Water",
        moves: ["Psychic", "Heal Pulse", "Trick Room", "Protect"],
      },
      {
        id: 4,
        name: "Amoonguss",
        item: "Mental Herb",
        ability: "Regenerator",
        tera: "Fire",
        moves: ["Pollen Puff", "Rage Powder", "Spore", "Protect"],
      },
      {
        id: 5,
        name: "Iron Hands",
        item: "Sitrus Berry",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Fake Out", "Protect"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Haze", "Protect"],
      },
    ],
  },
  {
    rank: 27,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ice",
        moves: ["Ice Spinner", "Sucker Punch", "Protect", "Sacred Sword"],
      },
      {
        id: 2,
        name: "Tyranitar",
        item: "Life Orb",
        ability: "Sand Stream",
        tera: "Rock",
        moves: ["Rock Slide", "Crunch", "Dragon Dance", "Protect"],
      },
      {
        id: 3,
        name: "Iron Hands",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Fake Out", "Wild Charge", "Protect"],
      },
      {
        id: 4,
        name: "Volcarona",
        item: "Leftovers",
        ability: "Flame Body",
        tera: "Grass",
        moves: ["Heat Wave", "Giga Drain", "Quiver Dance", "Protect"],
      },
      {
        id: 5,
        name: "Dragonite",
        item: "Choice Band",
        ability: "Inner Focus",
        tera: "Normal",
        moves: ["Extreme Speed", "Giga Impact", "Dragon Claw", "Rock Slide"],
      },
      {
        id: 6,
        name: "Amoonguss",
        item: "Rocky Helmet",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Spore", "Rage Powder", "Pollen Puff", "Protect"],
      },
    ],
  },
  {
    rank: 33,
    pokemon: [
      {
        id: 1,
        name: "Indeedee ♀",
        item: "Psychic Seed",
        ability: "Psychic Surge",
        tera: "Psychic",
        moves: ["Dazzling Gleam", "Helping Hand", "Follow Me", "Trick Room"],
      },
      {
        id: 2,
        name: "Armarouge",
        item: "Twisted Spoon",
        ability: "Flash Fire",
        tera: "Fire",
        moves: ["Expanding Force", "Armor Cannon", "Wide Guard", "Trick Room"],
      },
      {
        id: 3,
        name: "Kingambit",
        item: "Safety Goggles",
        ability: "Defiant",
        tera: "Dark",
        moves: ["Kowtow Cleave", "Iron Head", "Sucker Punch", "Swords Dance"],
      },
      {
        id: 4,
        name: "Torkoal",
        item: "Charcoal",
        ability: "Drought",
        tera: "Fire",
        moves: ["Eruption", "Flamethrower", "Earth Power", "Clear Smog"],
      },
      {
        id: 5,
        name: "Hatterene",
        item: "Life Orb",
        ability: "Magic Bounce",
        tera: "Psychic",
        moves: ["Psychic", "Dazzling Gleam", "Mystical Fire", "Trick Room"],
      },
      {
        id: 6,
        name: "Annihilape",
        item: "Choice Scarf",
        ability: "Defiant",
        tera: "Fighting",
        moves: ["Final Gambit", "Close Combat", "Shadow Claw", "U-turn"],
      },
    ],
  },
  {
    rank: 30,
    pokemon: [
      {
        id: 1,
        name: "Wo-Chien",
        item: "Leftovers",
        ability: "Tablets of Ruin",
        tera: "Fire",
        moves: ["Giga Drain", "Leech Seed", "Pollen Puff", "Protect"],
      },
      {
        id: 2,
        name: "Glimmora",
        item: "Focus Sash",
        ability: "Toxic Debris",
        tera: "Grass",
        moves: ["Sludge Bomb", "Energy Ball", "Power Gem", "Spiky Shield"],
      },
      {
        id: 3,
        name: "Gothitelle",
        item: "Sitrus Berry",
        ability: "Shadow Tag",
        tera: "Normal",
        moves: ["Fake Out", "Heal Pulse", "Psychic", "Protect"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Steel",
        moves: ["Dazzling Gleam", "Shadow Ball", "Perish Song", "Protect"],
      },
      {
        id: 5,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Flare Blitz", "Will-O-Wisp", "Extreme Speed", "Protect"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
    ],
  },
  {
    rank: 31,
    pokemon: [
      {
        id: 1,
        name: "Arcanine",
        item: "Assault Vest",
        ability: "Intimidate",
        tera: "Fighting",
        moves: ["Flare Blitz", "Play Rough", "Extreme Speed", "Close Combat"],
      },
      {
        id: 2,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Ghost",
        moves: ["Shadow Ball", "Dazzling Gleam", "Perish Song", "Protect"],
      },
      {
        id: 3,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Fire",
        moves: ["Dark Pulse", "Heat Wave", "Snarl", "Overheat"],
      },
      {
        id: 4,
        name: "Gothitelle",
        item: "Sitrus Berry",
        ability: "Shadow Tag",
        tera: "Flying",
        moves: ["Psychic", "Taunt", "Fake Out", "Protect"],
      },
      {
        id: 5,
        name: "Amoonguss",
        item: "Covert Cloak",
        ability: "Regenerator",
        tera: "Dark",
        moves: ["Leaf Storm", "Pollen Puff", "Rage Powder", "Spore"],
      },
      {
        id: 6,
        name: "Iron Bundle",
        item: "Booster Energy",
        ability: "Quark Drive",
        tera: "Ghost",
        moves: ["Protect", "Freeze-Dry", "Hydro Pump", "Encore"],
      },
    ],
  },
  {
    rank: 34,
    pokemon: [
      {
        id: 1,
        name: "Garganacl",
        item: "Leftovers",
        ability: "Purifying Salt",
        tera: "Bug",
        moves: ["Salt Cure", "Wide Guard", "Recover", "Protect"],
      },
      {
        id: 2,
        name: "Gothitelle",
        item: "Sitrus Berry",
        ability: "Shadow Tag",
        tera: "Dark",
        moves: ["Psychic", "Protect", "Trick Room", "Fake Out"],
      },
      {
        id: 3,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Moonblast", "Shadow Ball", "Perish Song", "Protect"],
      },
      {
        id: 4,
        name: "Ting-Lu",
        item: "Figy Berry",
        ability: "Vessel of Ruin",
        tera: "Poison",
        moves: ["Stomping Tantrum", "Ruination", "Heavy Slam", "Protect"],
      },
      {
        id: 5,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Volt Switch", "Fake Out"],
      },
      {
        id: 6,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Steel",
        moves: ["Flamethrower", "Snarl", "Will-O-Wisp", "Protect"],
      },
    ],
  },
  {
    rank: 32,
    pokemon: [
      {
        id: 1,
        name: "Flutter Mane",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Shadow Ball", "Moonblast", "Protect"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Choice Scarf",
        ability: "Beads of Ruin",
        tera: "Ghost",
        moves: ["Heat Wave", "Snarl", "Dark Pulse", "Overheat"],
      },
      {
        id: 3,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Drain Punch", "Wild Charge", "Volt Switch", "Fake Out"],
      },
      {
        id: 4,
        name: "Farigiraf",
        item: "Throat Spray",
        ability: "Armor Tail",
        tera: "Normal",
        moves: ["Hyper Voice", "Psychic", "Trick Room", "Protect"],
      },
      {
        id: 5,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
      {
        id: 6,
        name: "Dragonite",
        item: "Lum Berry",
        ability: "Inner Focus",
        tera: "Flying",
        moves: ["Extreme Speed", "Tera Blast", "Ice Spinner", "Tailwind"],
      },
    ],
  },
  {
    rank: 37,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Protect", "Sacred Sword", "Ice Spinner", "Sucker Punch"],
      },
      {
        id: 2,
        name: "Azumarill",
        item: "Assault Vest",
        ability: "Huge Power",
        tera: "Water",
        moves: ["Aqua Jet", "Liquidation", "Ice Spinner", "Play Rough"],
      },
      {
        id: 3,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Spore", "Rage Powder", "Pollen Puff", "Clear Smog"],
      },
      {
        id: 4,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Protect", "Shadow Ball", "Moonblast", "Dazzling Gleam"],
      },
      {
        id: 5,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Protect", "Flare Blitz", "Snarl", "Will-O-Wisp"],
      },
      {
        id: 6,
        name: "Dragonite",
        item: "Choice Band",
        ability: "Inner Focus",
        tera: "Flying",
        moves: ["Extreme Speed", "Tera Blast", "Low Kick", "Dragon Claw"],
      },
    ],
  },
  {
    rank: 42,
    pokemon: [
      {
        id: 1,
        name: "Chien-Pao",
        item: "Life Orb",
        ability: "Sword of Ruin",
        tera: "Ice",
        moves: ["protect", "Ice Spinner", "Sucker Punch", "Sacred Sword"],
      },
      {
        id: 2,
        name: "Amoonguss",
        item: "Rocky Helmet",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Rage Powder", "Giga Drain", "Spore", "Clear Smog"],
      },
      {
        id: 3,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Protect", "Haze"],
      },
      {
        id: 4,
        name: "Pelipper",
        item: "Focus Sash",
        ability: "Drizzle",
        tera: "Water",
        moves: ["Tailwind", "Hurricane", "Protect", "Hydro Pump"],
      },
      {
        id: 5,
        name: "Scizor",
        item: "Choice band",
        ability: "Technician",
        tera: "Water",
        moves: ["Bullet Punch", "Close Combat", "Pounce", "Tera Blast"],
      },
      {
        id: 6,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Dark",
        moves: ["Stomping Tantrum", "Payback", "Throat Chop", "Rock Slide"],
      },
    ],
  },
  {
    rank: 41,
    pokemon: [
      {
        id: 1,
        name: "Murkrow",
        item: "Eviolite",
        ability: "Prankster",
        tera: "Ghost",
        moves: ["Tailwind", "Sunny Day", "Quash", "Foul Play"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Covert Cloak",
        ability: "Beads of Ruin",
        tera: "Fairy",
        moves: ["Heat Wave", "Dark Pulse", "Snarl", "Protect"],
      },
      {
        id: 3,
        name: "Brute Bonnet",
        item: "Black Glasses",
        ability: "Protosynthesis",
        tera: "Dark",
        moves: ["Sucker Punch", "Spore", "Seed Bomb", "Crunch"],
      },
      {
        id: 4,
        name: "Great Tusk",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Ground",
        moves: ["Headlong Rush", "Close Combat", "Protect", "Earthquake"],
      },
      {
        id: 5,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Protect", "Dazzling Gleam", "Moonblast", "Shadow Ball"],
      },
      {
        id: 6,
        name: "Farigiraf",
        item: "Colbur Berry",
        ability: "Armor Tail",
        tera: "Water",
        moves: ["Hyper Voice", "Twin Beam", "Trick Room", "Imprison"],
      },
    ],
  },
  {
    rank: 39,
    pokemon: [
      {
        id: 1,
        name: "Corviknight",
        item: "Safety Goggles",
        ability: "Mirror Armor",
        tera: "Ghost",
        moves: ["Brave Bird", "Roost", "U-turn", "Bulk Up"],
      },
      {
        id: 2,
        name: "Iron Hands",
        item: "Assault Vest",
        ability: "Quark Drive",
        tera: "Fire",
        moves: ["Drain Punch", "Thunder Punch", "Volt Switch", "Heavy Slam"],
      },
      {
        id: 3,
        name: "Indeedee ♀",
        item: "Psychic Seed",
        ability: "Psychic Surge",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Follow Me", "Helping Hand", "Trick Room"],
      },
      {
        id: 4,
        name: "Chi-Yu",
        item: "Life Orb",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Heat Wave", "Dark Pulse", "Nasty Plot", "Protect"],
      },
      {
        id: 5,
        name: "Lilligant",
        item: "Focus Sash",
        ability: "Chlorophyll",
        tera: "Grass",
        moves: ["Energy Ball", "Sleep Powder", "After You", "Protect"],
      },
      {
        id: 6,
        name: "Torkoal",
        item: "Sitrus Berry",
        ability: "Drought",
        tera: "Flying",
        moves: ["Eruption", "Heat Wave", "Yawn", "Protect"],
      },
    ],
  },
  {
    rank: 35,
    pokemon: [
      {
        id: 1,
        name: "Mimikyu",
        item: "Life Orb",
        ability: "Disguise",
        tera: "Ghost",
        moves: ["Play Rough", "Shadow Claw", "Shadow Sneak", "Curse"],
      },
      {
        id: 2,
        name: "Baxcalibur",
        item: "Clear Amulet",
        ability: "Thermal Exchange",
        tera: "Ground",
        moves: ["Glaive Rush", "Icicle Crash", "Earthquake", "Protect"],
      },
      {
        id: 3,
        name: "Amoonguss",
        item: "Sitrus Berry",
        ability: "Regenerator",
        tera: "Water",
        moves: ["Spore", "Pollen Puff", "Rage Powder", "Protect"],
      },
      {
        id: 4,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Water",
        moves: ["Bulldoze", "Fissure", "Heavy Slam", "Ruination"],
      },
      {
        id: 5,
        name: "Slither Wing",
        item: "Safety Goggles",
        ability: "Protosynthesis",
        tera: "Fire",
        moves: ["Brick Break", "Protect", "Leech Life", "Bulk Up"],
      },
      {
        id: 6,
        name: "Talonflame",
        item: "Covert Cloak",
        ability: "Gale Wings",
        tera: "Flying",
        moves: ["Flare Blitz", "Brave Bird", "Tailwind", "Protect"],
      },
    ],
  },
  {
    rank: 40,
    pokemon: [
      {
        id: 1,
        name: "Ting-Lu",
        item: "Sitrus Berry",
        ability: "Vessel of Ruin",
        tera: "Water",
        moves: ["Stomping Tantrum", "Ruination", "Snarl", "Protect"],
      },
      {
        id: 2,
        name: "Chien-Pao",
        item: "Focus Sash",
        ability: "Sword of Ruin",
        tera: "Ghost",
        moves: ["Icicle Crash", "Sacred Sword", "Sucker Punch", "Protect"],
      },
      {
        id: 3,
        name: "Arcanine",
        item: "Mago Berry",
        ability: "Intimidate",
        tera: "Grass",
        moves: ["Flare Blitz", "Will-O-Wisp", "Snarl", "Protect"],
      },
      {
        id: 4,
        name: "Dragonite",
        item: "Lum Berry",
        ability: "Multiscale",
        tera: "Normal",
        moves: ["Dragon Claw", "Extreme Speed", "Iron Head", "Tailwind"],
      },
      {
        id: 5,
        name: "Gholdengo",
        item: "Leftovers",
        ability: "Good as Gold",
        tera: "Water",
        moves: ["Make It Rain", "Shadow Ball", "Nasty Plot", "Protect"],
      },
      {
        id: 6,
        name: "Scizor",
        item: "Life Orb",
        ability: "Technician",
        tera: "Fire",
        moves: ["Bullet Punch", "U-turn", "Swords Dance", "Protect"],
      },
    ],
  },
  {
    rank: 36,
    pokemon: [
      {
        id: 1,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Water",
        moves: ["Flare Blitz", "Snarl", "Will-O-Wisp", "Protect"],
      },
      {
        id: 2,
        name: "Iron Bundle",
        item: "Focus Sash",
        ability: "Quark Drive",
        tera: "Grass",
        moves: ["Hydro Pump", "Freeze-Dry", "Icy Wind", "Protect"],
      },
      {
        id: 3,
        name: "Garganacl",
        item: "Leftovers",
        ability: "Purifying Salt",
        tera: "Ghost",
        moves: ["Salt Cure", "Recover", "Wide Guard", "Protect"],
      },
      {
        id: 4,
        name: "Wo-Chien",
        item: "Sitrus Berry",
        ability: "Tablets of Ruin",
        tera: "Fire",
        moves: ["Ruination", "Protect", "Knock Off", "Leech Seed"],
      },
      {
        id: 5,
        name: "Glimmora",
        item: "Covert Cloak",
        ability: "Toxic Debris",
        tera: "Rock",
        moves: ["Earth Power", "Power Gem", "Mortal Spin", "Spiky Shield"],
      },
      {
        id: 6,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Wave Crash", "Jet Punch", "Encore", "Protect"],
      },
    ],
  },
  {
    rank: 38,
    pokemon: [
      {
        id: 1,
        name: "Flutter Mane",
        item: "Focus Sash",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Shadow Ball", "Moonblast", "Protect"],
      },
      {
        id: 2,
        name: "Chi-Yu",
        item: "Life Orb",
        ability: "Beads of Ruin",
        tera: "Grass",
        moves: ["Heat Wave", "Dark Pulse", "Tera Blast", "Protect"],
      },
      {
        id: 3,
        name: "Scizor",
        item: "Sitrus Berry",
        ability: "Technician",
        tera: "Fire",
        moves: ["Bullet Punch", "Close Combat", "Feint", "Protect"],
      },
      {
        id: 4,
        name: "Roaring Moon",
        item: "Booster Energy",
        ability: "Protosynthesis",
        tera: "Flying",
        moves: ["Acrobatics", "Throat Chop", "Tailwind", "Protect"],
      },
      {
        id: 5,
        name: "Farigiraf",
        item: "Throat Spray",
        ability: "Armor Tail",
        tera: "Normal",
        moves: ["Hyper Voice", "Psychic", "Trick Room", "Protect"],
      },
      {
        id: 6,
        name: "Iron Bundle",
        item: "Covert Cloak",
        ability: "Quark Drive",
        tera: "Ghost",
        moves: ["Freeze-Dry", "Hydro Pump", "Icy Wind", "Protect"],
      },
    ],
  },
  {
    rank: 43,
    pokemon: [
      {
        id: 1,
        name: "Ting-Lu",
        item: "Assault Vest",
        ability: "Vessel of Ruin",
        tera: "Water",
        moves: ["Ruination", "Earthquake", "Heavy Slam", "Throat Chop"],
      },
      {
        id: 2,
        name: "Flutter Mane",
        item: "Life Orb",
        ability: "Protosynthesis",
        tera: "Fairy",
        moves: ["Dazzling Gleam", "Moonblast", "Shadow Ball", "Protect"],
      },
      {
        id: 3,
        name: "Annihilape",
        item: "Leftovers",
        ability: "Defiant",
        tera: "Poison",
        moves: ["Drain Punch", "Rage Fist", "Bulk Up", "Protect"],
      },
      {
        id: 4,
        name: "Maushold",
        item: "Covert Cloak",
        ability: "Friend Guard",
        tera: "Ghost",
        moves: ["Beat Up", "Taunt", "Follow Me", "Protect"],
      },
      {
        id: 5,
        name: "Palafin",
        item: "Mystic Water",
        ability: "Zero to Hero",
        tera: "Water",
        moves: ["Jet Punch", "Wave Crash", "Haze", "Protect"],
      },
      {
        id: 6,
        name: "Arcanine",
        item: "Safety Goggles",
        ability: "Intimidate",
        tera: "Grass",
        moves: ["Extreme Speed", "Flare Blitz", "Will-O-Wisp", "Protect"],
      },
    ],
  },
];
export default pokeData;
